version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source npm dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo installing dependencies
      - npm run start
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - node_modules/**/*
    - src/*
    - package.json